{
 "title": "imported_unknowd_default_dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "SHOW TAG VALUES WITH  KEY = \"name\""
   },
   {
    "name": "Topic",
    "query": "SHOW TAG VALUES WITH KEY = \"channel\""
   },
   {
    "name": "Publisher",
    "query": "SHOW TAG VALUES WITH KEY = \"publisher\""
   },
   { "name": "DB", "query": "influxdb" }
  ]
 },
 "panels": [
  {
   "title": "$Sensors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "repeat": "Sensors",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "raw",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "messages",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Sampling Rate",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "repeat": "Sensors",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current $Sensors SR ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "repeat": "Sensors",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "control",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Sensors$/" }
     ]
    }
   ]
  }
 ]
}